### ISSUE TITLE
Bug report: cannot import name 'compress' from 'scipy'

### ISSUE THREAD

**Issue by Hocnonsense** [cdanielmachado/reframed#25]
Recently I try to run `carveme` but failed, this is the log:
```bash
$ carve a.faa -o a.xml                                             
Traceback (most recent call last):
  File "/mnt/envs/carveme/bin/carve", line 5, in <module>       
    from carveme.cli.carve import main
  File "/mnt/envs/carveme/lib/python3.11/site-packages/carveme/__init__.py", line 5, in <module>
    from reframed.solvers.solver import default_parameters, Parameter                                      
  File "/mnt/envs/carveme/lib/python3.11/site-packages/reframed/__init__.py", line 13, in <module>
    from .core.transformation import make_irreversible, simplify, gpr_transform                            
  File "/mnt/envs/carveme/lib/python3.11/site-packages/reframed/core/transformation.py", line 5, in <module>
    from ..cobra.variability import blocked_reactions
  File "/mnt/envs/carveme/lib/python3.11/site-packages/reframed/cobra/variability.py", line 4, in <module>
    from .thermodynamics import llFBA
  File "/mnt/envs/carveme/lib/python3.11/site-packages/reframed/cobra/thermodynamics.py", line 7, in <module>
    from scipy import compress
ImportError: cannot import name 'compress' from 'scipy' (/mnt/envs/carveme/lib/python3.11/site-packages/scipy/__init__.py)                                                  
$ python
Python 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:43:09) [GCC 12.3.0] on linux              
Type "help", "copyright", "credits" or "license" for more information.                                     
>>> from scipy.linalg import svd
press
>>> from scipy import compress
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'compress' from 'scipy' (mnt/envs/carveme/lib/python3.11/site-packages/scipy/__init__.py)    
>>> from numpy import compress   
>>> exit
$ pip list
Package         Version
--------------- ------------
carveme         1.6.1
mpmath          1.3.0
numpy           1.26.3
pandas          2.2.0
pip             23.3.2
python-dateutil 2.8.2
python-libsbml  5.20.2
pytz            2023.3.post1
reframed        1.5.0
scipy           1.12.0
setuptools      69.0.3
six             1.16.0
sympy           1.12
tzdata          2023.4
wheel           0.42.0                                                                          
```

Should `compress` be load from numpy instead of scipy, thanks!

**Comment by sirno** [comment]
`pip install 'scipy<1.12.0'`

**Comment by cdanielmachado** [comment]
Should be fixed now :)
